baseURL = 'https://ciglenecki.github.io/'
languageCode = 'en-us'
title = 'Matej Ciglenečki'
theme = 'matej'

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    lineNos = false
    guessSyntax = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params.meta]
  favicon = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'
